create table RECIPES (
	ID SERIAL PRIMARY KEY,
	RECIPE_NAME varchar(100) NOT NULL,
	BODY varchar(2000) NOT NULL,
	AUTHOR varchar(100) NOT NULL,
	AUTHOR_ID int NOT NULL,
	PUBLISH_DATE DATE NOT NULL
	 );